services:
  - type: web
    name: standoff-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        fromService:
          type: web
          name: standoff-server
          property: port
      - key: MONGODB_URI
        value: mongodb://mongo:odPQUCRuWAiCqADMYBQwRecDahZgVhUN@turntable.proxy.rlwy.net:25506
      - key: MONGODB_DB
        value: v2_standoff